#
# SPDX-FileCopyrightText: Copyright 2022-2025 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
fail_fast: false
default_install_hook_types: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
        exclude: \.cp?p?$
      - id: trailing-whitespace
        stages: [pre-commit]
        exclude: '\.patch$'
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: detect-private-key
        stages: [pre-commit]
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-added-large-files
        args: ['--maxkb=100']
        stages: [pre-commit]
        exclude: '\.patch$'
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        args: [--whitespaces-count, '4']
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        pass_filenames: true
        stages: [pre-commit]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        stages: [pre-commit]
  - repo: https://github.com/fsfe/reuse-tool.git
    rev: v5.1.1
    hooks:
      - id: reuse
        args: [lint]
        stages: [pre-commit]
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: 1.4.3
    hooks:
      - id: cmakelint
        stages: [pre-commit]
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-i]
        stages: [pre-commit]
